#!/usr/bin/env python3

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import String

BURGER_MAX_LIN_VEL = 0.22
BURGER_MAX_ANG_VEL = 2.84

CONST_ANG_VEL = 1.42
CONST_LIN_VEL = 0.11


class BotMover:
    def __init__(self):
        self.move = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
        self.command = rospy.Subscriber('app_command', String, self.command_callback)
        
        self.max_lin = BURGER_MAX_LIN_VEL
        self.max_ang = BURGER_MAX_ANG_VEL
        
        self.cmd_vel = Twist()
        self.cmd_vel.linear.x  = 0.0
        self.cmd_vel.linear.y  = 0.0
        self.cmd_vel.linear.z  = 0.0
        self.cmd_vel.angular.x = 0.0
        self.cmd_vel.angular.y = 0.0
        self.cmd_vel.angular.z = 0.0


    def command_callback(self, msg):
        '''
        Callback on /app_command subscriber - modify self.cmd_vel 
        and publish it to /cmd_vel
        '''

        button = msg.data
        
        if button == 'up':
            self.cmd_vel.linear.x = CONST_LIN_VEL

        elif button == 'down':
            self.cmd_vel.linear.x = -CONST_LIN_VEL

        elif button == 'left':
            self.cmd_vel.angular.z = CONST_ANG_VEL

        elif button == 'right':
            self.cmd_vel.angular.z = -CONST_ANG_VEL

        elif button == "none":
            self.cmd_vel.linear.x = 0.0 
            self.cmd_vel.angular.z = 0.0

        elif button == 'stop':
            self.cmd_vel.linear.x = 0.0 
            self.cmd_vel.angular.z = 0.0
            print("Stopping the movement!")
            self.move.publish(self.cmd_vel)
            return
        
        else:
            return

        print(f"Currently: linear vel {self.cmd_vel.linear.x}, angular vel {self.cmd_vel.angular.z}")

        self.move.publish(self.cmd_vel)


    def run(self):
        while not rospy.is_shutdown():
            rospy.spin()



if __name__ == "__main__":
    rospy.init_node('bot_mover')
    bot = BotMover()
    
    try:
        bot.run()
    except rospy.ROSInterruptException:
        pass
    finally:
        twist = Twist()
        twist.linear.x = 0.0 
        twist.linear.y = 0.0 
        twist.linear.z = 0.0
        twist.angular.x = 0.0 
        twist.angular.y = 0.0 
        twist.angular.z = 0.0
        bot.move.publish(twist)
