#!/usr/bin/env python3

import rospy
from std_msgs.msg import String, Bool


class FeedbackThread:
    def __init__(self):
        
        self.flag = False
        self.const_info = rospy.Publisher('x_pos', String, queue_size = 1)
        self.listener = rospy.Subscriber('client_flag', Bool, self.callback)
#        self.client_info = rospy.Publisher('client_data', UdpClientData, queue_size = 1)

    
    def callback(self, message):
        self.flag = message.data


    def run(self):
        '''
        Run the server, let it listen and react to messages
        '''
        
        while not rospy.is_shutdown():
            x = 0
            while self.flag:
                if x % 2 == 0:
                    self.const_info.publish("1.27")
                else:
                    self.const_info.publish("1.30")
                x += 1





if __name__ == "__main__":
    
    rospy.init_node('feedback')
    
    feedback = FeedbackThread()

    try:
        feedback.run()
    except rospy.ROSInterruptException:
        pass

